# Generated by Django 2.2.5 on 2019-09-26 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=30)),
                ('team_desc', models.TextField(max_length=500)),
            ],
        ),
    ]
