# Generated by Django 2.2.5 on 2019-09-26 01:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_members',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
